import Mathlib.Probability.Process.Adapted
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic
import Mathlib.MeasureTheory.Measure.Prod
import Mathlib.MeasureTheory.Measure.Dirac.Basic
import Mathlib.MeasureTheory.Measure.Typeclasses.Probability
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic

/-!
# Hypothesis structure for AX-01 and AX-02 (`ledger/AXIOMS.md`)

One structure, `Upstream.HJMScheduled`, whose fields are, in the order of the ledger:

* the data (the "Common setting" of the ledger): a probability measure `μ` and a filtration
  `ℱ` on the sample space `Ω` (the type `Ω` and its ambient σ-algebra `m₀` are parameters of
  the structure so that downstream files can use ordinary instances), the dimension `d` of the
  Brownian motion, the number `N` of scheduled dates, the dates `τ 0 = 0 < τ 1 < … < τ N`
  (the encoding of Claim 002, `lean/Standalone/LemmaA.lean`), the initial curve `f₀`, the drift
  `α`, the volatility `σ` and the curve jumps `ξ`;
* the standing hypotheses (S7), `f₀_measurable` … `ξ_integrable`;
* the two axioms, `drift_integrated` (AX-01) and `jump_martingale` (AX-02).

Spelling choices that the ledger left to Lean:

* Progressive measurability of `α(t, T, ω)` in the source's sense (measurable for
  `𝒫 ⊗ ℬ(ℝ₊)`) is `IsStronglyProgressive` of `t ↦ ((T, ω) ↦ α t T ω)` for the filtration
  `paramFiltration ℱ : t ↦ ℬ(ℝ) ⊗ ℱ t` on `ℝ × Ω`; the same for `σ`.
* The integrability conditions of Assumption 3.3(ii), (iii), (v) are stated with the lower
  Lebesgue integral `∫⁻` of the nonnegative integrand, so that `< ⊤` is exactly "finite"
  without a separate integrability side condition. They are imposed `μ`-a.s. and for every
  `T > 0` (S7).
* `f₀_locallyIntegrable` is Assumption 3.3(i) as written: `∫_0^T |f(0, u)| du < ∞` for every
  `T > 0`, i.e. `IntegrableOn f₀ (Set.Icc 0 T)`.
* The jump `ξ n` is only constrained for `1 ≤ n ≤ N`: `T_0 = 0` is an interval endpoint, not a
  jump date (S4), so `ξ 0` and `ξ n` for `n > N` are unused data.
* `ℱ_(t)⁻` of AX-02 is `leftLimit ℱ t = ⨆ s < t, ℱ s`, the σ-algebra generated by
  `⋃_{s < t} ℱ s`. The conditional expectation is Mathlib's `condExp` (`μ[f | m]`); it is `0`
  on non-integrable `f`, so the field forces integrability of `exp (-∫ ξ)` by itself, as the
  ledger intends (audit note (c) on AX-02).
* In `drift_integrated`, `(Q ⊗ dt)`-a.e. on `Ω × [0, T]` is `∀ᵐ p ∂(μ.prod (volume.restrict
  (Set.Icc 0 T)))` with `p = (ω, t)`; the integrals are Mathlib's interval integrals, the
  `ℝ^d`-valued one in `EuclideanSpace ℝ (Fin d)` with its Euclidean norm.

The Brownian motion `W` and the forward-rate equation (3.2) are not fields (ledger, "Common
setting"). `HJMScheduled.nonvacuityInstance` is the non-vacuity instance: a one-point space,
`d = N = 1`, `τ n = n`, with nonzero continuous drift and volatility (`α t u = (u - t)⁺³ / 2`,
`σ t u = (u - t)⁺ • e`) that satisfy AX-01 pointwise, and `ξ = 0`.

Re-synced field by field on 2026-09-22 against the ledger as amended at ffff1bb73: the
amendments of that day add the common setting and the entries AX-03 to AX-08, all of which name
`Upstream.ItoCalculus` (`lean/Upstream/ItoCalculus.lean`), and leave the text of AX-01 and
AX-02, their "Lean:" lines and their `Audit: ok` lines (ledger/AUDIT_LOG.md 2026-09-21)
unchanged, so the data, the standing hypotheses (S7) and the two axiom fields above stand as
written.
Re-synced against the ledger at 99e79d64e (2026-09-23): AX-01 and AX-02
retain the same statements and fields. The new AX-09 entry is represented only by
`Upstream.Predictability` in `lean/Upstream/Predictability.lean`; it adds no field
to this structure and changes neither its hypotheses nor its instance.
-/

open MeasureTheory

namespace Upstream

variable {Ω : Type*} {m₀ : MeasurableSpace Ω}

set_option warn.classDefReducibility false in
/-- `ℱ_(t)⁻`: the σ-algebra generated by `⋃_{s < t} ℱ s` (AX-02). A σ-algebra used as data,
not as an instance, hence the disabled reducibility warning. -/
def leftLimit (ℱ : Filtration ℝ m₀) (t : ℝ) : MeasurableSpace Ω :=
  ⨆ s < t, ℱ s

lemma leftLimit_le (ℱ : Filtration ℝ m₀) (t : ℝ) : leftLimit ℱ t ≤ m₀ :=
  iSup₂_le fun s _ => ℱ.le s

lemma prod_mono {X Y : Type*} {m₁ m₁' : MeasurableSpace X} {m₂ m₂' : MeasurableSpace Y}
    (h₁ : m₁ ≤ m₁') (h₂ : m₂ ≤ m₂') : m₁.prod m₂ ≤ m₁'.prod m₂' :=
  sup_le_sup (MeasurableSpace.comap_mono h₁) (MeasurableSpace.comap_mono h₂)

/-- The filtration `t ↦ ℬ(ℝ) ⊗ ℱ t` on `ℝ × Ω`, used to say that a coefficient `(t, T, ω) ↦
α t T ω` is progressively measurable in the source's sense (Assumption 3.3(ii), (iii)). -/
def paramFiltration (ℱ : Filtration ℝ m₀) :
    Filtration ℝ (Prod.instMeasurableSpace : MeasurableSpace (ℝ × Ω)) where
  seq t := MeasurableSpace.prod inferInstance (ℱ t)
  mono' _ _ hst := prod_mono le_rfl (ℱ.mono hst)
  le' t := prod_mono le_rfl (ℱ.le t)

/-- The hypotheses of AX-01 and AX-02, field by field as in `ledger/AXIOMS.md`. -/
structure HJMScheduled (Ω : Type*) [m₀ : MeasurableSpace Ω] where
  /-- The risk-neutral measure `Q`. -/
  μ : Measure Ω
  [isProbabilityMeasure : IsProbabilityMeasure μ]
  /-- The filtration `(F_t)_{t ≥ 0}`. -/
  ℱ : Filtration ℝ m₀
  /-- Dimension of the Brownian motion; `σ` takes values in `ℝ^d`. -/
  d : ℕ
  /-- Number of scheduled dates `T_1 < … < T_N`. -/
  N : ℕ
  /-- The dates `T_0 = 0 < T_1 < … < T_N`; only `τ n` for `n ≤ N` is used. -/
  τ : ℕ → ℝ
  τ_zero : τ 0 = 0
  τ_strictMono : StrictMonoOn τ (Set.Iic N)
  /-- The initial curve `f(0, ·)`. -/
  f₀ : ℝ → ℝ
  /-- The drift `α(t, T)(ω)`. -/
  α : ℝ → ℝ → Ω → ℝ
  /-- The volatility `σ(t, T)(ω) ∈ ℝ^d`. -/
  σ : ℝ → ℝ → Ω → EuclideanSpace ℝ (Fin d)
  /-- The curve jump `ξ_n(u)(ω)` at the date `T_n`, `1 ≤ n ≤ N`. -/
  ξ : ℕ → ℝ → Ω → ℝ
  -- (S7), Assumption 3.3(i)
  f₀_measurable : Measurable f₀
  f₀_locallyIntegrable : ∀ T : ℝ, 0 < T → IntegrableOn f₀ (Set.Icc 0 T)
  -- (S7), Assumption 3.3(ii)
  α_progMeasurable : IsStronglyProgressive (paramFiltration ℱ) fun t (p : ℝ × Ω) => α t p.1 p.2
  α_zero_of_lt : ∀ t T ω, T < t → α t T ω = 0
  α_integrable : ∀ T : ℝ, 0 < T → ∀ᵐ ω ∂μ,
    ∫⁻ u in Set.Icc 0 T, ∫⁻ s in Set.Icc 0 u, ENNReal.ofReal |α s u ω| < ⊤
  -- (S7), Assumption 3.3(iii)
  σ_progMeasurable : IsStronglyProgressive (paramFiltration ℱ) fun t (p : ℝ × Ω) => σ t p.1 p.2
  σ_zero_of_lt : ∀ t T ω, T < t → σ t T ω = 0
  σ_integrable : ∀ T : ℝ, 0 < T → ∀ᵐ ω ∂μ,
    ∑ i, ∫⁻ u in Set.Icc 0 T,
      (∫⁻ s in Set.Icc 0 u, ENNReal.ofReal ((σ s u ω i) ^ 2)) ^ (1 / 2 : ℝ) < ⊤
  -- (S7), Assumption 3.3(v)
  ξ_measurable : ∀ n, 1 ≤ n → n ≤ N →
    Measurable[MeasurableSpace.prod inferInstance (ℱ (τ n))] fun p : ℝ × Ω => ξ n p.1 p.2
  ξ_zero_of_lt : ∀ n, 1 ≤ n → n ≤ N → ∀ u ω, u < τ n → ξ n u ω = 0
  ξ_integrable : ∀ n, 1 ≤ n → n ≤ N → ∀ T : ℝ, 0 < T → ∀ᵐ ω ∂μ,
    ∫⁻ u in Set.Icc 0 T, ENNReal.ofReal |ξ n u ω| < ⊤
  /-- AX-01: for every `T > 0`, `(Q ⊗ dt)`-a.e. on `Ω × [0, T]`,
  `∫_t^T α(t, u) du = ½ |∫_t^T σ(t, u) du|²`. -/
  drift_integrated : ∀ T : ℝ, 0 < T →
    ∀ᵐ p ∂(μ.prod (volume.restrict (Set.Icc 0 T))),
      ∫ u in p.2..T, α p.2 u p.1 = (1 / 2 : ℝ) * ‖∫ u in p.2..T, σ p.2 u p.1‖ ^ 2
  /-- AX-02: for every `1 ≤ n ≤ N` and `T ≥ T_n`, `Q`-a.s.,
  `E[exp (-∫_{T_n}^T ξ_n(u) du) | F_{T_n -}] = 1`. -/
  jump_martingale : ∀ n, 1 ≤ n → n ≤ N → ∀ T : ℝ, τ n ≤ T →
    μ[fun ω => Real.exp (-(∫ u in τ n..T, ξ n u ω)) | leftLimit ℱ (τ n)] =ᵐ[μ] 1

attribute [instance] HJMScheduled.isProbabilityMeasure

/-! ### Non-vacuity instance

A deterministic model on the one-point space with `d = N = 1`, `τ n = n`, `f₀ = 0`, `ξ = 0`,
and the nonzero, continuous coefficients

* `σ t u = (u - t)⁺ • e` with `e` the unit vector of `ℝ^1`,
* `α t u = (u - t)⁺³ / 2`,

where `x⁺ = max x 0`. For every `t, T` (not only `t ≤ T`), `∫_t^T (u - t)⁺ du = (T - t)⁺² / 2`
and `∫_t^T (u - t)⁺³ / 2 du = (T - t)⁺⁴ / 8 = ½ ((T - t)⁺² / 2)²`, so `drift_integrated` holds
pointwise; `jump_martingale` holds since `ξ = 0`. The coefficients vanish for `u < t`, are
continuous (hence progressively measurable) and bounded on bounded sets (hence the
integrability fields). -/

namespace HJMScheduled

/-- `∫_t^T (u - t)⁺^(n+1) du = (T - t)^(n+2) / (n+2)` for `t ≤ T`, and `0` for `T < t`. -/
lemma integral_max_pow (t T : ℝ) (n : ℕ) :
    ∫ u in t..T, max (u - t) 0 ^ (n + 1) =
      if t ≤ T then (T - t) ^ (n + 2) / (n + 2) else 0 := by
  split_ifs with h
  · rw [intervalIntegral.integral_congr_Ioo_of_le h (g := fun u => (u - t) ^ (n + 1))
      (fun u hu => by simp [max_eq_left (by linarith [hu.1] : 0 ≤ u - t)])]
    rw [intervalIntegral.integral_comp_sub_right (fun x => x ^ (n + 1)) t, sub_self,
      integral_pow]
    push_cast
    ring
  · rw [intervalIntegral.integral_symm,
      intervalIntegral.integral_congr_Ioo_of_le (le_of_lt (not_le.1 h)) (g := fun _ => 0)
        (fun u hu => by simp [max_eq_right (by linarith [hu.2] : u - t ≤ 0)])]
    simp

/-- The bound `(u - t)⁺ ≤ T` for `0 ≤ t` and `0 ≤ u ≤ T`. -/
lemma max_sub_le {t u T : ℝ} (ht : 0 ≤ t) (hu0 : 0 ≤ u) (hu : u ≤ T) : max (u - t) 0 ≤ T :=
  max_le (by linarith) (by linarith)

/-- `∫⁻_{[0,b]} ofReal (f x) ≤ ofReal c * ofReal b` when `0 ≤ f ≤ c` on `[0, b]`. -/
lemma setLIntegral_Icc_le {f : ℝ → ℝ} {b c : ℝ} (h : ∀ x ∈ Set.Icc 0 b, f x ≤ c) :
    ∫⁻ x in Set.Icc 0 b, ENNReal.ofReal (f x) ≤ ENNReal.ofReal c * ENNReal.ofReal b := by
  calc ∫⁻ x in Set.Icc 0 b, ENNReal.ofReal (f x)
      ≤ ∫⁻ _ in Set.Icc 0 b, ENNReal.ofReal c :=
        lintegral_mono_ae (ae_restrict_of_forall_mem measurableSet_Icc
          fun x hx => ENNReal.ofReal_le_ofReal (h x hx))
    _ = ENNReal.ofReal c * ENNReal.ofReal b := by
        rw [setLIntegral_const, Real.volume_Icc, sub_zero]

/-- The unit vector of `ℝ^1`. -/
noncomputable def e : EuclideanSpace ℝ (Fin 1) := EuclideanSpace.single 0 1

lemma norm_e : ‖e‖ = 1 := by simp [e]

lemma e_apply (i : Fin 1) : e i = 1 := by simp [e, Fin.eq_zero i]

/-- The non-vacuity instance described above. -/
noncomputable def nonvacuityInstance : HJMScheduled Unit where
  μ := Measure.dirac ()
  ℱ := Filtration.const ℝ inferInstance le_rfl
  d := 1
  N := 1
  τ n := (n : ℝ)
  τ_zero := Nat.cast_zero
  τ_strictMono := Nat.strictMono_cast.strictMonoOn _
  f₀ := fun _ => 0
  α := fun t u _ => max (u - t) 0 ^ 3 / 2
  σ := fun t u _ => max (u - t) 0 • e
  ξ := fun _ _ _ => 0
  f₀_measurable := measurable_const
  f₀_locallyIntegrable := fun _ _ => integrableOn_zero
  α_progMeasurable := fun i => by
    show StronglyMeasurable fun p : Set.Iic i × (ℝ × Unit) => max (p.2.1 - (p.1 : ℝ)) 0 ^ 3 / 2
    exact Continuous.stronglyMeasurable (by fun_prop)
  α_zero_of_lt := fun t T _ h => by simp [max_eq_right (by linarith : T - t ≤ 0)]
  α_integrable := fun T hT => Filter.Eventually.of_forall fun _ => by
    have hb : ∀ u ∈ Set.Icc 0 T, ∀ s ∈ Set.Icc 0 u, |max (u - s) 0 ^ 3 / 2| ≤ T ^ 3 / 2 := by
      intro u hu s hs
      have h0 : 0 ≤ max (u - s) 0 := le_max_right _ _
      have h1 : max (u - s) 0 ≤ T := max_sub_le hs.1 hu.1 hu.2
      rw [abs_of_nonneg (by positivity)]
      have := pow_le_pow_left₀ h0 h1 3
      linarith
    calc ∫⁻ u in Set.Icc 0 T, ∫⁻ s in Set.Icc 0 u, ENNReal.ofReal |max (u - s) 0 ^ 3 / 2|
        ≤ ∫⁻ _ in Set.Icc 0 T, ENNReal.ofReal (T ^ 3 / 2) * ENNReal.ofReal T := by
          refine lintegral_mono_ae (ae_restrict_of_forall_mem measurableSet_Icc fun u hu => ?_)
          calc ∫⁻ s in Set.Icc 0 u, ENNReal.ofReal |max (u - s) 0 ^ 3 / 2|
              ≤ ENNReal.ofReal (T ^ 3 / 2) * ENNReal.ofReal u := setLIntegral_Icc_le (hb u hu)
            _ ≤ ENNReal.ofReal (T ^ 3 / 2) * ENNReal.ofReal T :=
                mul_le_mul' le_rfl (ENNReal.ofReal_le_ofReal hu.2)
      _ < ⊤ := by
          rw [setLIntegral_const, Real.volume_Icc]
          exact ENNReal.mul_lt_top (ENNReal.mul_lt_top ENNReal.ofReal_lt_top ENNReal.ofReal_lt_top)
            ENNReal.ofReal_lt_top
  σ_progMeasurable := fun i => by
    show StronglyMeasurable fun p : Set.Iic i × (ℝ × Unit) => max (p.2.1 - (p.1 : ℝ)) 0 • e
    exact Continuous.stronglyMeasurable (by fun_prop)
  σ_zero_of_lt := fun t T _ h => by simp [max_eq_right (by linarith : T - t ≤ 0)]
  σ_integrable := fun T hT => Filter.Eventually.of_forall fun _ => by
    have hb : ∀ u ∈ Set.Icc 0 T, ∀ s ∈ Set.Icc 0 u, (max (u - s) 0 • e) 0 ^ 2 ≤ T ^ 2 := by
      intro u hu s hs
      rw [PiLp.smul_apply, e_apply, smul_eq_mul, mul_one]
      exact pow_le_pow_left₀ (le_max_right _ _) (max_sub_le hs.1 hu.1 hu.2) 2
    rw [Fin.sum_univ_one]
    calc ∫⁻ u in Set.Icc 0 T,
          (∫⁻ s in Set.Icc 0 u, ENNReal.ofReal ((max (u - s) 0 • e) 0 ^ 2)) ^ (1 / 2 : ℝ)
        ≤ ∫⁻ _ in Set.Icc 0 T,
            (ENNReal.ofReal (T ^ 2) * ENNReal.ofReal T) ^ (1 / 2 : ℝ) := by
          refine lintegral_mono_ae (ae_restrict_of_forall_mem measurableSet_Icc fun u hu => ?_)
          refine ENNReal.rpow_le_rpow ?_ (by norm_num)
          calc ∫⁻ s in Set.Icc 0 u, ENNReal.ofReal ((max (u - s) 0 • e) 0 ^ 2)
              ≤ ENNReal.ofReal (T ^ 2) * ENNReal.ofReal u := setLIntegral_Icc_le (hb u hu)
            _ ≤ ENNReal.ofReal (T ^ 2) * ENNReal.ofReal T :=
                mul_le_mul' le_rfl (ENNReal.ofReal_le_ofReal hu.2)
      _ < ⊤ := by
          rw [setLIntegral_const, Real.volume_Icc]
          exact ENNReal.mul_lt_top
            (ENNReal.rpow_lt_top_of_nonneg (by norm_num)
              (ENNReal.mul_lt_top ENNReal.ofReal_lt_top ENNReal.ofReal_lt_top).ne)
            ENNReal.ofReal_lt_top
  ξ_measurable := fun _ _ _ => measurable_const
  ξ_zero_of_lt := fun _ _ _ _ _ _ => rfl
  ξ_integrable := fun _ _ _ _ _ => Filter.Eventually.of_forall fun _ => by simp
  drift_integrated := fun T _ => Filter.Eventually.of_forall fun p => by
    rw [intervalIntegral.integral_div, intervalIntegral.integral_smul_const, norm_smul, norm_e,
      mul_one, Real.norm_eq_abs, sq_abs]
    have h1 := integral_max_pow p.2 T 0
    have h3 := integral_max_pow p.2 T 2
    simp only [zero_add, pow_one] at h1
    rw [h1, h3]
    split_ifs <;> push_cast <;> ring
  jump_martingale := fun n _ _ T _ => by
    have h : (fun _ : Unit => Real.exp (-(∫ _ in (n : ℝ)..T, (0 : ℝ)))) = fun _ => (1 : ℝ) := by
      funext _; simp
    rw [h, condExp_const (leftLimit_le _ _)]
    exact Filter.Eventually.of_forall fun _ => rfl

end HJMScheduled

end Upstream
