import Upstream.LipschitzMarkov

/-!
# AX-13: Markov property of Lipschitz SDE solutions with time-dependent coefficients

The field specializes [vanhandel2007stochastic], Theorem 5.2.2 with Definition
3.1.8, as recorded in `ledger/AXIOMS.md`, AX-13. It is a separate structure over
an existing `ItoCalculus`, so no earlier consumer's hypotheses change, and it
reuses `BrownianDrivers6`, `Coefficients6` and `Solution6` of AX-06
(`lean/Upstream/LipschitzSDE.lean`) unchanged: the full Brownian-vector premise,
Borel coefficients jointly in time and state, globally Lipschitz in the state
with one constant uniform in time and bounded on boxes, with no regularity in
time, and the solution class with its (U4) diffusion domains, local drift
integrability and the equation with the supplied integral. The initial value is
square-integrable. Bounded Borel test functions are `BoundedBorel12` of AX-12
(`lean/Upstream/LipschitzMarkov.lean`), a predicate only.

The conclusion (AX-13.1) is, for one solution at a time, deterministic `s ≤ t`
and each bounded Borel `f` separately, that the conditional expectation of
`f (X t)` given `ℱ s` equals that given the sigma-algebra generated by `X s`,
almost surely. No transition function, composition law, independence of the
initial law, or statement at random times is asserted. No curve formula,
variance model or meeting schedule is a field.

The instance over `ItoCalculus.zeroDriverInstance` is vacuous: that base has
covariation density `c ≡ 0`, so the Brownian premise is false
(`LipschitzSDE.zeroDriver_not_brownian`) and the field holds for every
coefficient family and solution without exercising a Markov property. This is
permitted by rule 6 as amended on 2026-09-23 (Q-06) only together with the
following separate checks, in `premises_check` and `conclusion_check`:
(1) every premise but the Brownian one holds for one datum: zero coefficients
satisfy `Coefficients6`, a constant state satisfies every `Solution6` clause over
the zero-driver base, its initial value is square-integrable, `0 ≤ 0`, and
every constant test function satisfies `BoundedBorel12`;
(2) the conclusion (AX-13.1) holds for that constant solution, for all times and
every test function, both sides being `f x`, and is instantiated at a constant
test function known to satisfy the premise;
(3) every calculus of driver dimension zero satisfies `BrownianDrivers6`.
These checks give no nontrivial Brownian or Markov model. A faithful instance
would reconstruct textbook SDE theory, forbidden by Lean role duty 3b.
-/

open MeasureTheory ProbabilityTheory
open scoped NNReal

namespace Upstream

/-- The published AX-13 conclusion over an existing calculus structure. -/
structure LipschitzMarkovTime {Ω : Type*} [MeasurableSpace Ω] (h : ItoCalculus Ω) : Prop where
  markov_property : BrownianDrivers6 h → ∀ (n : ℕ)
    (b : ℝ≥0 × (Fin n → ℝ) → Fin n → ℝ)
    (σ : ℝ≥0 × (Fin n → ℝ) → Fin n → Fin h.m → ℝ),
    Coefficients6 b σ → ∀ X : ℝ≥0 → Ω → Fin n → ℝ,
    Solution6 h b σ (X 0) X → MemLp (X 0) 2 h.μ →
    ∀ s t : ℝ≥0, s ≤ t → ∀ f, BoundedBorel12 f →
      h.μ[f ∘ X t | h.ℱ s] =ᵐ[h.μ] h.μ[f ∘ X t | MeasurableSpace.comap (X s) inferInstance]

namespace LipschitzMarkovTime

/-- A genuine, but vacuous, model of the field over the zero-driver base: its
Brownian premise is false. No Markov conclusion is obtained from this instance. -/
theorem zeroDriverInstance : LipschitzMarkovTime ItoCalculus.zeroDriverInstance where
  markov_property := fun h => (LipschitzSDE.zeroDriver_not_brownian h).elim

/-- The constant solution used by the checks. -/
def constSolution (x : Fin 1 → ℝ) : ℝ≥0 → Unit → Fin 1 → ℝ := fun _ _ => x

/-- Check (1): every premise of the field except the Brownian one holds for zero
coefficients, a constant solution, and a constant test function. -/
lemma premises_check (x : Fin 1 → ℝ) (c : ℝ) :
    Coefficients6 (m := ItoCalculus.zeroDriverInstance.m)
      (fun _ : ℝ≥0 × (Fin 1 → ℝ) => (0 : Fin 1 → ℝ)) (fun _ => 0) ∧
    Solution6 ItoCalculus.zeroDriverInstance (fun _ => 0) (fun _ => 0)
      (constSolution x 0) (constSolution x) ∧
    MemLp (constSolution x 0) 2 ItoCalculus.zeroDriverInstance.μ ∧
    (0 : ℝ≥0) ≤ 0 ∧
    BoundedBorel12 (fun _ : Fin 1 → ℝ => c) :=
  ⟨LipschitzMarkov.coefficients6_zero_check 1 _, LipschitzMarkov.solution6_zero_check x,
    memLp_const x, le_rfl, LipschitzMarkov.boundedBorel12_const_check 1 c⟩

/-- Check (2): (AX-13.1) holds for the constant solution; both sides are `f x`. -/
lemma conclusion_check (x : Fin 1 → ℝ) (f : (Fin 1 → ℝ) → ℝ) (s t : ℝ≥0) :
    ItoCalculus.zeroDriverInstance.μ[f ∘ constSolution x t | ItoCalculus.zeroDriverInstance.ℱ s]
      =ᵐ[ItoCalculus.zeroDriverInstance.μ]
    ItoCalculus.zeroDriverInstance.μ[f ∘ constSolution x t |
      MeasurableSpace.comap (constSolution x s) inferInstance] := by
  have h1 := condExp_const (μ := ItoCalculus.zeroDriverInstance.μ)
    (ItoCalculus.zeroDriverInstance.ℱ.le s) (f x)
  have h2 := condExp_const (μ := ItoCalculus.zeroDriverInstance.μ)
    ((measurable_const : Measurable (constSolution x s)).comap_le) (f x)
  change ItoCalculus.zeroDriverInstance.μ[fun _ => f x | _] =ᵐ[_]
    ItoCalculus.zeroDriverInstance.μ[fun _ => f x | _]
  rw [h1]
  exact Filter.EventuallyEq.of_eq h2.symm

/-- Check (2) at a test function satisfying the premise, and times with `s ≤ t`. -/
lemma conclusion_const_check (x : Fin 1 → ℝ) (c : ℝ) (t : ℝ≥0) :
    BoundedBorel12 (fun _ : Fin 1 → ℝ => c) ∧ (0 : ℝ≥0) ≤ t ∧
    ItoCalculus.zeroDriverInstance.μ[(fun _ => c) ∘ constSolution x t |
        ItoCalculus.zeroDriverInstance.ℱ 0] =ᵐ[ItoCalculus.zeroDriverInstance.μ]
      ItoCalculus.zeroDriverInstance.μ[(fun _ => c) ∘ constSolution x t |
        MeasurableSpace.comap (constSolution x 0) inferInstance] :=
  ⟨LipschitzMarkov.boundedBorel12_const_check 1 c, zero_le, conclusion_check x _ 0 t⟩

/-- Check (3): the empty driver vector satisfies every Brownian-vector premise. -/
lemma brownianDrivers6_dimension_zero_check {Ω : Type*} [MeasurableSpace Ω]
    (h : ItoCalculus Ω) (hm : h.m = 0) : BrownianDrivers6 h :=
  LipschitzSDE.brownianDrivers6_of_dimension_zero h hm

end LipschitzMarkovTime
end Upstream
