import Standalone.ContinuousAggregationAmericanLower

/-! # Claim 054 (54-R): regression and product representation

Claim 046's model, **conditional on `GaussLaw`**, with a cutoff `0 ≤ A ≤ S ≤ H`.

The pre-`A` coordinates (`preIdx`) are the meeting shocks `Z_i` with `T_i ≤ A` and the Wiener
integrals `I(1_{[0,u]})`, `u ∈ [0, A]`. The latter are `Y_u` almost surely; every real `u` is used,
not only rationals. Each is a combination `Σ β_j Z_j + I f` (`preCoord`). `ycomb` is the
combination `Σ_{T_i ≤ A} Z_i + I(1_{[0,A]})`, which is `y_A` minus a constant almost surely.

`bil` is the covariance form `Σ β_i β'_i v_i + ∫_0^H f f' g` of two combinations. The regression
coefficient is `coef x = Cov(X_x, y_A)/V_A = bil(x, y)/bil(y, y)`, and the residual is
`resid x = X_x − coef x · ycomb`. `resAlg` is the σ-algebra `σ(r)` of all residuals. When
`V_A = 0`, Lean's `/0 = 0` makes `coef = 0`; every pre-`A` coordinate is then almost surely `0`,
and the statements hold with `resid = X`.

`regressionStatement`, (54-R):
* `resAlg` is a sub-σ-algebra, and the map `Γ = (id, (y_A, Ξ))` pushes `Q^A` to the product of
  `Q^A` on `resAlg` with `N(0, V_A) ⊗ λ_post`. On rectangles:
  `Q^A(B ∩ {(y_A, Ξ) ∈ C}) = Q^A(B) · (N(0, V_A) ⊗ λ_post)(C)` for `B ∈ σ(r)` and Borel `C`.
  In particular `σ(r)` is independent of `(y_A, Ξ)` under `Q^A`;
* the corrected filtration identity (54.7), before the right-continuous regularization: for
  `A ≤ s ∧ S`, `natural_s ∨ 𝒩_Q = (σ(r) ∨ (y_A, Ξ)⁻¹ σ(y, ξ_{≤s})) ∨ 𝒩_Q`, as equal σ-algebras of
  sets almost everywhere equal to a set of the respective σ-algebra. `σ(r) ∨ (y_A, Ξ)⁻¹
  σ(y, ξ_{≤s})` is `Γ⁻¹(σ(r) ⊗ σ(y, ξ_{≤s}))`.
-/

open MeasureTheory ProbabilityTheory Set

namespace Standalone.ContinuousAggregationRegression
open Standalone.DiffusionMeetingGauss (DiffModel GaussLaw)
open Standalone.DiffusionMeetingPricing (QS Qacc)
open Standalone.ContinuousAggregationCurve (yA)
open Standalone.ContinuousAggregationEuropean (State Xi)
open Standalone.ContinuousAggregationAmericanLower (natural postFilt)

variable {Ω : Type*} {N : ℕ}

/-- The pre-`A` coordinates: meetings with `T_i ≤ A`, and times `u ∈ [0, A]`. -/
abbrev preIdx (M : DiffModel Ω N) (A : ℝ) := {i : Fin N // M.T i ≤ A} ⊕ Icc (0 : ℝ) A

/-- The meeting weights of a pre-`A` coordinate. -/
def preβ (M : DiffModel Ω N) (A : ℝ) : preIdx M A → Fin N → ℝ
  | Sum.inl i => Pi.single i.1 1
  | Sum.inr _ => 0

/-- The integrand of a pre-`A` coordinate. -/
noncomputable def pref (M : DiffModel Ω N) (A : ℝ) : preIdx M A → ℝ → ℝ
  | Sum.inl _ => fun _ => 0
  | Sum.inr u => (Icc 0 u.1).indicator 1

/-- The pre-`A` coordinate `X_x = Σ β_j Z_j + I f`. -/
noncomputable def preCoord (M : DiffModel Ω N) (A : ℝ) (x : preIdx M A) (ω : Ω) : ℝ :=
  ∑ j, preβ M A x j * M.Z j ω + M.I (pref M A x) ω

/-- `Σ_{T_i ≤ A} Z_i + I(1_{[0,A]})`. -/
noncomputable def ycomb (M : DiffModel Ω N) (A : ℝ) (ω : Ω) : ℝ :=
  ∑ i, (if M.T i ≤ A then 1 else 0) * M.Z i ω + M.I ((Icc 0 A).indicator 1) ω

/-- The covariance form `Σ β_i β'_i v_i + ∫_0^H f f' g`. -/
noncomputable def bil (M : DiffModel Ω N) (H : ℝ) (β : Fin N → ℝ) (f : ℝ → ℝ) (β' : Fin N → ℝ)
    (f' : ℝ → ℝ) : ℝ :=
  ∑ i, β i * β' i * M.v i + ∫ s in (0:ℝ)..H, f s * f' s * M.g s

/-- The regression coefficient `Cov(X_x, y_A)/V_A`. -/
noncomputable def coef (M : DiffModel Ω N) (A H : ℝ) (x : preIdx M A) : ℝ :=
  bil M H (preβ M A x) (pref M A x) (fun i => if M.T i ≤ A then 1 else 0) ((Icc 0 A).indicator 1) /
    bil M H (fun i => if M.T i ≤ A then 1 else 0) ((Icc 0 A).indicator 1)
      (fun i => if M.T i ≤ A then 1 else 0) ((Icc 0 A).indicator 1)

/-- The residual `X_x − coef x · ycomb`. -/
noncomputable def resid (M : DiffModel Ω N) (A H : ℝ) (x : preIdx M A) (ω : Ω) : ℝ :=
  preCoord M A x ω - coef M A H x * ycomb M A ω

/-- `σ(r)`, generated by all residuals. -/
noncomputable def resAlg (M : DiffModel Ω N) (A H : ℝ) : MeasurableSpace Ω :=
  ⨆ x, MeasurableSpace.comap (resid M A H x) inferInstance

def regressionStatement : Prop := ∀ (Ω : Type) [m₀ : MeasurableSpace Ω] (N : ℕ) (Q : Measure Ω)
  [IsProbabilityMeasure Q] (M : DiffModel Ω N) (H : ℝ), GaussLaw M Q H →
  ∀ A S : ℝ, 0 ≤ A → A ≤ S → S ≤ H →
    resAlg M A H ≤ m₀ ∧
    (∀ B C, MeasurableSet[resAlg M A H] B → MeasurableSet C →
      QS M Q A (B ∩ (fun ω => (yA M A ω, Xi M A H ω)) ⁻¹' C) =
        QS M Q A B * ((gaussianReal 0 (Qacc M A).toNNReal).prod (Q.map (Xi M A H))) C) ∧
    ∀ s : ℝ, A ≤ min s S →
      eventuallyMeasurableSpace (natural M S s) (ae Q) =
        eventuallyMeasurableSpace (resAlg M A H ⊔ MeasurableSpace.comap
          (fun ω => (yA M A ω, Xi M A H ω)) (postFilt M A H S s)) (ae Q)

def statement : Prop := regressionStatement

end Standalone.ContinuousAggregationRegression
