import Standalone.ContinuousAggregationCurve
import Mathlib.Probability.Independence.Basic

/-! # Claim 054 (a): the level under the discount density

Claim 046's model, **conditional on `GaussLaw`**. For a cutoff `0 ≤ A ≤ H`, `Q^A` is
`DiffusionMeetingPricing.QS M Q A`, with density `B_A⁻¹/P(0, A)`, and `y_A = r_A − f₀(A)`
(`ContinuousAggregationCurve.yA`).

A *future driving increment* (`Future`) is `inc M β f = Σ β_i Z_i + I f` with `β_i = 0` unless
`T_i > A`, and `f` an `Integrand` on `[0, H]` vanishing on `[0, A]`. `futureAlg M H A` is the
σ-algebra generated by all of them.

`levelStatement`:
* under `Q^A`, `y_A ~ N(0, V_A)`, `V_A = Qacc M A`;
* the σ-algebra of all future driving increments is independent of `F_A` under `Q` and under
  `Q^A`, and `Q^A` agrees with `Q` on it (the family has the same joint law under both);
* the σ-algebra of all future driving increments is independent of `y_A` under `Q^A`, and so is
  each future driving increment.
-/

open MeasureTheory ProbabilityTheory

namespace Standalone.ContinuousAggregationLevel
open Standalone.DiffusionMeetingGauss (DiffModel GaussLaw Integrand)
open Standalone.DiffusionMeetingPricing (QS Qacc)
open Standalone.ContinuousAggregationCurve (yA)

variable {Ω : Type*} {N : ℕ}

/-- `Σ β_i Z_i + I f`. -/
noncomputable def inc (M : DiffModel Ω N) (β : Fin N → ℝ) (f : ℝ → ℝ) (ω : Ω) : ℝ :=
  ∑ i, β i * M.Z i ω + M.I f ω

/-- A future driving increment after `A`. -/
def Future (M : DiffModel Ω N) (H A : ℝ) (β : Fin N → ℝ) (f : ℝ → ℝ) : Prop :=
  (∀ i, β i ≠ 0 → A < M.T i) ∧ Integrand f 0 H ∧ ∀ s, f s ≠ 0 → A < s

/-- The σ-algebra of all future driving increments. -/
noncomputable def futureAlg [MeasurableSpace Ω] (M : DiffModel Ω N) (H A : ℝ) :
    MeasurableSpace Ω :=
  ⨆ (p : (Fin N → ℝ) × (ℝ → ℝ)) (_ : Future M H A p.1 p.2),
    MeasurableSpace.comap (inc M p.1 p.2) inferInstance

def levelStatement : Prop := ∀ (Ω : Type) [MeasurableSpace Ω] (N : ℕ) (Q : Measure Ω)
  [IsProbabilityMeasure Q] (M : DiffModel Ω N) (H : ℝ), GaussLaw M Q H →
  ∀ A : ℝ, 0 ≤ A → A ≤ H →
    HasLaw (yA M A) (gaussianReal 0 (Qacc M A).toNNReal) (QS M Q A) ∧
    Indep (futureAlg M H A) (M.F A) Q ∧
    Indep (futureAlg M H A) (M.F A) (QS M Q A) ∧
    (∀ s, MeasurableSet[futureAlg M H A] s → QS M Q A s = Q s) ∧
    Indep (futureAlg M H A) (MeasurableSpace.comap (yA M A) inferInstance) (QS M Q A) ∧
    ∀ β f, Future M H A β f → IndepFun (yA M A) (inc M β f) (QS M Q A)

def statement : Prop := levelStatement

end Standalone.ContinuousAggregationLevel
