import Standalone.SpliceQuasiExponentialAssembly
import Novel.SpliceQuasiExponentialConsistencyProof

namespace Novel.SpliceQuasiExponentialAssemblyProof

theorem spliceQuasiExponentialAssembly : Standalone.SpliceQuasiExponentialAssembly.statement := ⟨Novel.SpliceQuasiExponentialAlgebraProof.spliceQuasiExponentialAlgebra, Novel.SpliceQuasiExponentialKeyProof.spliceQuasiExponentialKey, Novel.SpliceQuasiExponentialCrossProof.spliceQuasiExponentialCross, Novel.SpliceCrossTermCurveProof.step, Novel.SpliceQuasiExponentialBlockProof.spliceQuasiExponentialBlock, Novel.SpliceQuasiExponentialCurveProof.spliceQuasiExponentialCurve, Novel.SpliceQuasiExponentialConsistencyProof.spliceQuasiExponentialConsistency⟩

end Novel.SpliceQuasiExponentialAssemblyProof
