import Standalone.SpliceCrossTermAssembly
import Novel.SpliceCrossTermAnalyticProof
import Novel.SpliceCrossTermAlphaProof
import Novel.SpliceCrossTermSufficiencyProof

namespace Novel.SpliceCrossTermAssemblyProof

theorem spliceCrossTermAssembly : Standalone.SpliceCrossTermAssembly.statement := ⟨Novel.SpliceCrossTermAnalyticProof.spliceCrossTermAnalytic, Novel.SpliceCrossTermDriftProof.spliceCrossTermDrift, Novel.SpliceCrossTermAlphaProof.spliceCrossTermAlpha, Novel.SpliceCrossTermCurveProof.spliceCrossTermCurve, Novel.SpliceCrossTermNecessityProof.spliceCrossTermNecessity, Novel.SpliceCrossTermOpenProof.spliceCrossTermOpen, Novel.SpliceCrossTermUncorrelatedProof.spliceCrossTermUncorrelated, Novel.SpliceCrossTermConsistencyProof.spliceCrossTermConsistency, Novel.SpliceCrossTermSufficiencyProof.spliceCrossTermSufficiency⟩

end Novel.SpliceCrossTermAssemblyProof
